l = [5, 4, 3, 2, 1]
print(f"Base list: {l}")
l.sort()
print(f"Sorted list: {l}")
l.reverse()
print(f"Reversed list: {l}")
l2 = l.copy()
l2[0] = -1
print(f"Copied l to l2, modified l2")
print(f"\tl:{l}")
print(f"\tl2:{l2}")
l.append(42)
print(f"Appended 42 to l: {l}")
p = l.pop()
print(f"Popped 42 off l, p: {p}, l:{l}") 
print(f"index of 1 {l.index(1)}")
l.extend(l2)
print(f"Extended l2 onto l: {l}")
print(f"Number of 1s in l: {l.count(1)}")
l.remove(1)
print(f"Remove a one from l: {l}")
l.clear()
print(f"Cleared l: {l}")